---
downloads: ~/.ansible-downloads/

configure_osx: true
configure_dock: true
configure_dotfiles: true
configure_emacs: true
configure_nix: true

dotfiles_repo: "https://github.com/chrischambers/dots.git"
chezmoi_user_home: "{{ ansible_env.HOME }}"
chezmoi_directory: "{{ chezmoi_user_home }}/.local/share/chezmoi"

emacs_user_home: "{{ ansible_env.HOME }}"
chemacs_repo: "https://github.com/plexus/chemacs2.git"
emacsen_directory: "{{ emacs_user_home }}/emacsen"
emacs_config_repo: "git@github.com:chrischambers/emacs-latest.git"
emacs_config_location: "{{ emacsen_directory }}/mine"

ebooks_source_directory: "{{ ansible_env.HOME }}/Dropbox/ebooks"
ebooks_destination_path: "{{ ansible_env.HOME }}/Ebooks"

nix_user: "{{ ansible_env.USER }}"

dockitems_remove:
  - Launchpad
  - Safari
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - TV
  - Music
  - Podcasts
  - News
  - Keynote
  - Numbers
  - Pages

dockitems_persist:
  - name: iTerm
    path: "/Applications/iTerm.app"
    pos: 1
  - name: Emacs
    path: "/opt/homebrew/Cellar/emacs-plus@29/29.0.90/Emacs.app"
    pos: 2
  - name: "Brave Browser"
    path: "/Applications/Brave Browser.app"
    pos: 3
  - name: "Firefox Developer Edition"
    path: "/Applications/Firefox Developer Edition.app"
    pos: 4
  - name: "Tor Browser"
    path: "/Applications/Tor Browser.app"
    pos: 5
  - name: "Discord"
    path: "/Applications/Discord.app"
    pos: 6
  - name: "Steam"
    path: "/opt/homebrew/Caskroom/steam/4.0/Steam.app"
    pos: 7
  - name: "calibre"
    path: "/Applications/calibre.app"
    pos: 8
  - name: "App Store"
    path: "/System/Applications/App Store.app"
    pos: 9
  - name: "System Preferences"
    path: "/System/Applications/System Preferences.app"
    pos: 10

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

homebrew_uninstalled_packages:
  - emacs

homebrew_cask_uninstalled_apps:
  - emacs

homebrew_installed_packages:
  ## Misc:
  # ----------------------------------------------------------------------
  - djvu2pdf

  # Programming:
  # ----------------------------------------------------------------------
  - cmake
  - editorconfig
  - git
  - git-delta          # prettier diffing, esp. for git
  - subversion         # required for some of the font casks, and legacy codebases
  # - node
  - ormolu             # haskell formatter
  - shellcheck         # shell script linter
  - yamllint

  ## Clojure:
  # ----------------------------------------------------------------------
  - clojure/tools/clojure
  - leiningen
  - exercism

  # Dotfiles:
  # ----------------------------------------------------------------------
  # - ansible # Installed via Pip.
  - chezmoi
  - stow

  # Shell:
  # ----------------------------------------------------------------------
  - zsh
  - tmux
  - starship

  # CLI utils:
  # ----------------------------------------------------------------------
  - aria2              # file/torrent download
  - bat
  - coreutils          # essential GNU programs
  - dos2unix
  - fd
  - ffmpeg             # video file manipulation
  - fzf
  - gnu-sed            # GNU sed (OSX bundled with BSD sed)
  - jq
  - neofetch           # swag
  - pywhat
  - rename
  - ripgrep
  - urlview
  - vifm               # file browser w/ vim keys

  ## http/download
  # ----------------------------------------------------------------------
  - curl
  - httpie
  - wget

  ## CLI browsers
  # ----------------------------------------------------------------------
  - lynx
  - w3m

  ## ls
  # ----------------------------------------------------------------------
  - broot
  - exa
  - lsd
  - zoxide

  ## top
  # ----------------------------------------------------------------------
  - bpytop
  - htop

  ## Improved help facilities
  # ----------------------------------------------------------------------
  - cheat
  - tldr

  # Writing:
  # ----------------------------------------------------------------------
  - aspell
  - wordnet

  # Editing:
  # ----------------------------------------------------------------------
  - {name: "d12frosted/emacs-plus/emacs-plus@29", install_options: "with-imagemagick,with-modern-mzaplotnik-icon,with-native-comp,with-no-frame-refocus,with-dbus"}
  - neovim
  - ditaa
  - notmuch
  - plantuml
  - watchexec         # performance improvement: emacs w/ straight

  # Sandboxing:
  # ----------------------------------------------------------------------
  - direnv
  - lxc
  - pyenv
  - rbenv

  # Database:
  # ----------------------------------------------------------------------
  - postgresql

  # Security:
  # ----------------------------------------------------------------------
  - pass
  - pinentry-mac

  # ??
  # ----------------------------------------------------------------------
  # - gcc
  # - make
  # - cmake

  # - asciidoc
  # - automake          # required for mailvelope
  # - filebrowser/tap/filebrowser
  # - html2text
  # - libiconv
  # - libmetalink
  # - libproxy
  # - libscrypt
  # - libvterm
  # - libxml2
  # - luajit
  # - mailutils

  # - poppler           # pdf manipulation. pdf-tools?
  # - texinfo           # documentation format for GNU
  # - transmission-cli  # torrent client

homebrew_taps:
  - homebrew/bundle
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/cask-versions
  - homebrew/services
  - clojure/tools
  - d12frosted/emacs-plus
  - dskecse/tap              # mozart 2
  # - filebrowser/tap

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - hpedrorodrigues/tools/dockutil   # temporary cask: required for sorting dock

  - brave-browser
  - firefox-developer-edition
  - tor-browser

  - anki
  - calibre
  - db-browser-for-sqlite
  - discord
  - dropbox
  - iterm2
  - keyboard-maestro
  - kindle
  - licecap
  - mactex
  # - meld
  - mozart2
  - racket
  - soulseek
  - steam
  - transmission
  - vlc

  - font-et-book
  - font-fira-code
  - font-hack
  - font-hack-nerd-font
  - font-ibm-plex
  - font-iosevka
  - font-roboto-mono
  - font-sauce-code-pro-nerd-font
  - font-source-code-pro
  - font-ubuntu

  # - pycharm
  # - textmate
  # - vimr
  # - visual-studio-code

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
