---
downloads: ~/.ansible-downloads/

configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

homebrew_installed_packages:
  # Programming:
  # ----------------------------------------------------------------------
  - editorconfig
  - git
  # - node
  - ormolu             # haskell formatter
  - shellcheck         # shell script linter

  ## Clojure:
  # ----------------------------------------------------------------------
  - clojure/tools/clojure
  - leiningen
  - exercism

  # Dotfiles:
  # ----------------------------------------------------------------------
  # - ansible # Installed via Pip.
  - chezmoi
  - stow

  # Shell:
  # ----------------------------------------------------------------------
  - zsh
  - tmux
  - starship

  # CLI utils:
  # ----------------------------------------------------------------------
  - aria2              # file/torrent download
  - bat
  - coreutils          # essential GNU programs
  - dos2unix
  - fd
  - ffmpeg             # video file manipulation
  - fzf
  - gnu-sed            # GNU sed (OSX bundled with BSD sed)
  - jq
  - neofetch           # swag
  - pywhat
  - rename
  - ripgrep
  - urlview
  - vifm               # file browser w/ vim keys

  ## http/download
  # ----------------------------------------------------------------------
  - curl
  - httpie
  - wget

  ## CLI browsers
  # ----------------------------------------------------------------------
  - lynx
  - w3m

  ## ls
  # ----------------------------------------------------------------------
  - broot
  - exa
  - lsd
  - zoxide

  ## top
  # ----------------------------------------------------------------------
  - bpytop
  - htop

  ## Improved help facilities
  # ----------------------------------------------------------------------
  - cheat
  - tldr

  # Writing:
  # ----------------------------------------------------------------------
  - aspell
  - wordnet

  # Editing:
  # ----------------------------------------------------------------------
  - d12frosted/emacs-plus/emacs-plus@29
  - neovim
  - ditaa
  - plantuml
  - watchexec         # performance improvement: emacs w/ straight

  # Sandboxing:
  # ----------------------------------------------------------------------
  - direnv
  - lxc
  - pyenv
  - rbenv

  # Database:
  # ----------------------------------------------------------------------
  - postgresql

  # Security:
  # ----------------------------------------------------------------------
  - pass
  - pinentry-mac

  # ??
  # ----------------------------------------------------------------------
  # - gcc
  # - make
  # - cmake

  # - asciidoc
  # - automake          # required for mailvelope
  # - filebrowser/tap/filebrowser
  # - html2text
  # - libiconv
  # - libmetalink
  # - libproxy
  # - libscrypt
  # - libvterm
  # - libxml2
  # - luajit
  # - mailutils

  # - poppler           # pdf manipulation. pdf-tools?
  # - texinfo           # documentation format for GNU
  # - transmission-cli  # torrent client

homebrew_taps:
  # - homebrew/bundle
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  # - homebrew/cask-versions
  # - homebrew/services
  - clojure/tools
  - d12frosted/emacs-plus
  - dskecse/tap              # mozart 2
  # - filebrowser/tap

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - dropbox
  - firefox
  - google-chrome
  - handbrake
  - licecap
  - sequel-ace
  - slack
  - sublime-text
  - transmit
  - vagrant

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
