---
- name: Infer homebrew emacs-plus version
  ansible.builtin.shell: "brew info emacs-plus --json | jq '.[0].versions.stable'"
  register: emacs_version_info

- ansible.builtin.set_fact:
    emacs_version: "{{ emacs_version_info.stdout | trim('\"') }}"

- ansible.builtin.set_fact:
    emacs_major_version: "{{ emacs_version | splitext | first }}"

- name: Construct homebrew's Emacs.app path
  ansible.builtin.command:
    cmd: echo /opt/homebrew/Cellar/emacs-plus@{{ emacs_major_version}}/{{ emacs_version }}/Emacs.app
  register: emacs_homebrew_app_path

- name: Symlink homebrew Emacs.app to /Applications
  ansible.builtin.file:
    src: "{{ emacs_homebrew_app_path }}"
    dest: "/Applications/Emacs.app"
    state: link
  when: >
    src.stat.isdir is defined and
    src.stat.isdir and
    dest.stat.symlink is not defined

- name: Make sure emacsen directory is present
  ansible.builtin.file:
    path: "{{ emacsen_directory }}"
    state: directory
    mode: 0755

- name: Chemacs/another Emacs repo already installed at ~/.emacs.d?
  ansible.builtin.stat:
    path: "{{ emacs_user_home }}/.emacs.d/.git"
  register: chemacs_git_folder

- name: Clone Chemacs into ~/.emacs.d
  ansible.builtin.git:
    repo: "{{ chemacs_repo }}"
    dest: "{{ emacs_user_home }}/.emacs.d"
  when: not chemacs_git_folder.stat.exists

- name: "Emacs config already exists at {{ emacs_config_location }}?"
  ansible.builtin.stat:
    path: "{{ emacs_config_location }}/.git"
  register: emacs_config

- name: "Clone Emacs configuration into {{ emacs_config_location }}"
  ansible.builtin.git:
    repo: "{{ emacs_config_repo }}"
    dest: "{{ emacs_config_location }}"
  when: not emacs_config.stat.exists

- name: Provide Chemacs profile via template
  ansible.builtin.template:
    src: emacs-profiles.el
    dest: "{{ emacs_user_home }}/.emacs-profiles.el"
