---
- name: Make sure emacsen directory is present
  ansible.builtin.file:
    path: "{{ emacsen_directory }}"
    state: directory
    mode: 0755

- name: Detect if Chemacs/another Emacs repo is already installed at ~/.emacs.d
  ansible.builtin.stat:
    path: "{{ emacs_user_home }}/.emacs.d/.git"
  register: chemacs_git_folder

- name: Clone Chemacs into ~/.emacs.d
  ansible.builtin.git:
    repo: "{{ chemacs_repo }}"
    dest: "{{ emacs_user_home }}/.emacs.d"
  when: not chemacs_git_folder.stat.exists

- name: Clone Emacs configuration into ~/emacsen/mine
  ansible.builtin.git:
    repo: "{{ emacs_config_repo }}"
    dest: "{{ emacsen_directory }}/mine"

- name: Provide Chemacs profile via template
  ansible.builtin.template:
    src: emacs-profiles.el
    dest: "{{ emacs_user_home }}/.emacs-profiles.el"
