---
- name: Ebooks source available?
  ansible.builtin.stat:
    path: "{{ ebooks_source_directory }}"
  register: src

- name: Ebooks destination link already present?
  ansible.builtin.stat:
    path: "{{ ebooks_destination_path }}"
  register: dest

- name: Symlink Ebooks source folder to destination
  ansible.builtin.file:
    src: "{{ ebooks_source_directory }}"
    dest: "{{ ebooks_destination_path }}"
    state: link
  when: >
    src.stat.isdir is defined and
    src.stat.isdir and
    dest.stat.symlink is not defined
