---
- name: Check if nix-darwin flake.nix is present
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.config/nix/flake.nix"
  register: flake_nix_installed_result

- ansible.builtin.set_fact:
    flake_nix_installed: "{{ flake_nix_installed_result.rc }}"

- name: Create ~/.config/nix if necessary
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/nix"
    state: directory
    mode: "0544"
  when: not flake_nix_installed

- name: Create flake.nix from template if required
  ansible.builtin.template:
    src: flake.nix
    dest: "{{ ansible_env.HOME }}/.config/nix/flake.nix"
  register: flake_nix_from_template_result
  when: not flake_nix_installed

- ansible.builtin.set_fact:
    flake_nix_from_template: "{{ flake_nix_from_template.rc | default(false) }}"

- name: Create git repo if flake.nix was created from template
  # One of the stranger footguns when using Nix flakes is that all files
  # referenced by a flake must be checked into source control.
  ansible.builtin.shell: >
    git init {{ ansible_env.HOME }}/.config/nix &&
    git add flake.nix &&
    git commit -m 'Add flake.nix'
  when: flake_nix_from_template

- name: Bootstrap nix-darwin from flake
  ansible.builtin.command: >
    nix run nix-darwin
    --extra-experimental-features nix-command
    --extra-experimental-features flakes
    --
    switch
    --flake ~/.config/nix
