---
- name: Create ~/bin directory
  ansible.builtin.file:
    path: "{{ emacs_user_home }}/bin"
    state: directory

- name: Check if emacs-plus installed
  block:
    - name: "Run homebrew command to check emacs-plus installed"
      ansible.builtin.command: "brew list -1 emacs-plus"
    - name: "Store successful result"
      ansible.builtin.set_fact:
        emacs_plus_installed: true
  rescue:
    - name: "Store unsuccessful result"
      ansible.builtin.set_fact:
        emacs_plus_installed: false

- name: Symlink homebrew Emacs.app to /Applications
  ansible.builtin.file:
    src: "{{ emacs_homebrew_root_path }}/Emacs.app"
    dest: "/Applications/Emacs.app"
    state: link
  when: >
    emacs_plus_installed and
    src.stat.isdir is defined and
    src.stat.isdir and
    dest.stat.symlink is not defined

- name: Symlink homebrew bin/emacs to ~/bin
  ansible.builtin.file:
    src: "{{ emacs_homebrew_root_path }}/bin/emacs"
    dest: "{{ emacs_user_home }}/bin/emacs"
    state: link
  when: >
    emacs_plus_installed and
    src.stat.exists is defined and
    src.stat.exists and
    dest.stat.symlink is not defined

- name: Symlink homebrew bin/emacsclient to ~/bin
  ansible.builtin.file:
    src: "{{ emacs_homebrew_root_path }}/bin/emacsclient"
    dest: "{{ emacs_user_home }}/bin/emacsclient"
    state: link
  when: >
    emacs_plus_installed and
    src.stat.exists is defined and
    src.stat.exists and
    dest.stat.symlink is not defined

- name: Make sure emacsen directory is present
  ansible.builtin.file:
    path: "{{ emacsen_directory }}"
    state: directory
    mode: "0755"

- name: Chemacs/another Emacs repo already installed at ~/.emacs.d?
  ansible.builtin.stat:
    path: "{{ emacs_user_home }}/.emacs.d/.git"
  register: chemacs_git_folder

- name: Clone Chemacs into ~/.emacs.d
  ansible.builtin.git:
    repo: "{{ chemacs_repo }}"
    dest: "{{ emacs_user_home }}/.emacs.d"
    version: master
  when: >
    chemacs_git_folder.stat.exists is defined and
    not chemacs_git_folder.stat.exists

- name: "Emacs config already exists at {{ emacs_config_location }}?"
  ansible.builtin.stat:
    path: "{{ emacs_config_location }}/.git"
  register: emacs_config

- name: "Clone Emacs configuration into {{ emacs_config_location }}"
  ansible.builtin.git:
    repo: "{{ emacs_config_repo }}"
    dest: "{{ emacs_config_location }}"
    version: master
  when: >
    emacs_config.stat.exists is defined and
    not emacs_config.stat.exists

- name: Provide Chemacs profile via template
  ansible.builtin.template:
    src: emacs-profiles.el
    dest: "{{ emacs_user_home }}/.emacs-profiles.el"
