(("default"   .       ((user-emacs-directory . "{{ emacsen_directory}}/mine")))
 ("spacemacs" .       ((user-emacs-directory . "{{ emacsen_directory}}/spacemacs")))
 ("corgi" .           ((user-emacs-directory . "{{ emacsen_directory}}/corgi")))
 ("crafted-emacs"   . ((user-emacs-directory . "{{ emacsen_directory}}/crafted-emacs/home")))
 ("prelude"   .       ((user-emacs-directory . "{{ emacsen_directory}}/prelude")))
 ("doom"      .       ((user-emacs-directory . "{{ emacsen_directory}}/doom-emacs")
                       (env .    (("DOOMDIR" . "{{ emacsen_directory}}/doom-emacs/doom.d"))))))
