---
### Restart macOS preferences
#
# Description:
#
#   This handler will kill the three primary macOS processes that need to be
#   restarted after common defaults write commands Note that this does not start
#   the processes, however, macOS restarts them automatically.
#
#   TODO: Find a module for working with macOS processes, the services module
#   does not work on macOS.

## system
- name: Restart Finder
  command: killall Finder
  listen: "restart macos preferences"
- name: Restart Dock
  command: killall Dock
  listen: "restart macos preferences"
- name: Restart SystemUIServer
  command: killall SystemUIServer
  listen: "restart macos preferences"
